/**
 * PORTARIA REGISTRO - Exports de Constants
 * Centraliza todas as constantes do módulo
 * Data: 24/03/2026
 */

export {
  PORTARIA_TIPOS,
  PORTARIA_TIPOS_LABEL,
  PORTARIA_TIPOS_DESCRICAO,
  PORTARIA_TIPOS_LIST,
  PORTARIA_TIPOS_VEICULO,
  PORTARIA_TIPOS_VEICULO_LIST,
  PORTARIA_TIPOS_DOCUMENTO,
  PORTARIA_TIPOS_DOCUMENTO_LIST,
  PORTARIA_ORIGEM,
  PORTARIA_ORIGEM_LABEL,
} from './portariaRegistroTypes';

export {
  PORTARIA_STATUS,
  PORTARIA_STATUS_LIST,
  PORTARIA_STATUS_COLORS,
  PORTARIA_STATUS_BG_COLORS,
  PORTARIA_PAGINATION_DEFAULTS,
  PORTARIA_DATA_DEFAULTS,
} from './portariaRegistroStatus';

export {
  PORTARIA_VALIDATION_ERRORS,
  PORTARIA_API_ERRORS,
  PORTARIA_GENERIC_ERRORS,
  PORTARIA_ERROR_MESSAGES,
} from './portariaRegistroErrors';

export {
  PORTARIA_SUCCESS_MESSAGES,
  PORTARIA_CONFIRMATION_MESSAGES,
  PORTARIA_INFO_MESSAGES,
  PORTARIA_PLACEHOLDERS,
  PORTARIA_FIELD_LABELS,
  PORTARIA_FIELD_DESCRIPTIONS,
} from './portariaRegistroMessages';
